//! Partner cases models.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Partner case status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CaseStatus {
    Creating,
    Open,
    Pending,
    Solved,
    Closed,
}

/// Partner case type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CaseType {
    GeneralEnquiry,
}

/// Partner case object.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PartnerCase {
    /// Case ID (generated by Wise).
    pub id: i64,
    /// Case status.
    pub status: CaseStatus,
    /// Case type.
    #[serde(rename = "type")]
    pub case_type: CaseType,
    /// External partner ID for tracking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// When the case was created.
    pub created_at: DateTime<Utc>,
    /// When the case was last updated.
    pub updated_at: DateTime<Utc>,
}

/// Case details.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CaseDetails {
    /// Transfer ID (optional).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transfer_id: Option<i64>,
    /// Profile ID (optional).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<i64>,
    /// User ID (required).
    pub user_id: i64,
}

/// Request to create a partner case.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateCaseRequest {
    /// Case type (must be GENERAL_ENQUIRY).
    #[serde(rename = "type")]
    pub case_type: CaseType,
    /// Case subject (no PII).
    pub subject: String,
    /// Case details.
    pub details: CaseDetails,
    /// External partner ID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// Case description (max 65535 chars).
    pub description: String,
}

/// Comment author.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommentAuthor {
    Partner,
    WiseAgent,
}

/// Case comment.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CaseComment {
    /// Comment ID.
    pub id: i64,
    /// Comment body (may include markdown).
    pub plain_body: String,
    /// Comment author.
    pub author: CommentAuthor,
    /// When the comment was created.
    pub created_at: DateTime<Utc>,
}

/// Response for listing case comments.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaseCommentsResponse {
    /// Message if comments are empty due to CREATING status.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// List of comments (newest first).
    pub comments: Vec<CaseComment>,
}

/// Request to add a comment to a case.
#[derive(Debug, Clone, Serialize)]
pub struct AddCaseCommentRequest {
    /// Comment text (may include markdown, max 65535 chars).
    pub comment: String,
}
